DROP TABLE IF EXISTS TBL_BOOKS;
  
CREATE TABLE TBL_BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  descripcion VARCHAR(250),
  autor VARCHAR(250) DEFAULT NULL,
  fechaPublicacion DATE NOT NULL
);